spring:
  application:
    name: xsapi-backend
  # default dev
  profiles:
    active: dev
  #  swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session
  session:
    # todo redis
    # store-type: redis
    # 30 days over
    timeout: 2592000
  # dataSource
  # todo replace settings
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xsapi
    username: root
    password: root
  # Redis
  # todo replace settings
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # Elasticsearch settings
  # todo replace settings
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # file upload
  servlet:
    multipart:
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 overTerm
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# wx
wx:
  #
  # todo replace settings
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # wx open
  # todo replace settings
  open:
    appId: xxx
    appSecret: xxx
# object
# todo replace settings
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx